micronaut:
  application:
    name: micronsul
  server:
    port: 8110
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
netty:
  default:
    allocator:
      max-order: 3
